### ISSUE TITLE
File dialogs on setup screen can be opened multiple times

### ISSUE THREAD

**Issue by BraqueDown** [N1nDr0id/FuserCustomSongManager#1]
Five instances of the "Fuser install directory" dialog.

![image](https://github.com/N1nDr0id/FuserCustomSongManager/assets/43602802/0ac2732a-789b-4eb1-b4ee-174cbbcdf895)

**Comment by BraqueDown** [comment]
This also applies to the same buttons in the Configuration menu once setup is complete.

![image](https://github.com/N1nDr0id/FuserCustomSongManager/assets/43602802/bbe49020-0f3a-482f-97ec-7bce00128475)

**Comment by N1nDr0id** [comment]
Thank you for notifying me of this. A fix for this will be in the works soon.
